# Generated by Django 3.2.6 on 2021-10-01 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeiroBimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeira_nota_Português', models.FloatField(verbose_name='Nota de Língua Portuguesa')),
                ('primeira_nota_Matemática', models.FloatField(verbose_name='Nota de Matemática')),
                ('primeira_nota_História', models.FloatField(verbose_name='Nota de História')),
                ('primeira_nota_Geografia', models.FloatField(verbose_name='Nota de Geografia')),
                ('primeira_nota_Ciências', models.FloatField(verbose_name='Nota de Ciências')),
                ('primeiro_bimestre_faltas', models.IntegerField(verbose_name='Faltas no Bimestre')),
            ],
            options={
                'verbose_name': 'Primeiro Bimestre',
                'verbose_name_plural': 'Primeiro Bimestre',
            },
        ),
        migrations.CreateModel(
            name='QuartoBimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarta_nota_Português', models.FloatField(verbose_name='Nota de Língua Portuguesa')),
                ('quarta_nota_Matemática', models.FloatField(verbose_name='Nota de Matemática')),
                ('quarta_nota_História', models.FloatField(verbose_name='Nota de História')),
                ('quarta_nota_Geografia', models.FloatField(verbose_name='Nota de Geografia')),
                ('quarta_nota_Ciências', models.FloatField(verbose_name='Nota de Ciências')),
                ('quarto_bimestre_faltas', models.IntegerField(verbose_name='Faltas no Bimestre')),
            ],
            options={
                'verbose_name': 'Quarto Bimestre',
                'verbose_name_plural': 'Quarto Bimestre',
            },
        ),
        migrations.CreateModel(
            name='SegundoBimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda_nota_Português', models.FloatField(verbose_name='Nota de Língua Portuguesa')),
                ('segunda_nota_Matemática', models.FloatField(verbose_name='Nota de Matemática')),
                ('segunda_nota_História', models.FloatField(verbose_name='Nota de História')),
                ('segunda_nota_Geografia', models.FloatField(verbose_name='Nota de Geografia')),
                ('segunda_nota_Ciências', models.FloatField(verbose_name='Nota de Ciências')),
                ('segundo_bimestre_faltas', models.IntegerField(verbose_name='Faltas no Bimestre')),
            ],
            options={
                'verbose_name': 'Segundo Bimestre',
                'verbose_name_plural': 'Segundo Bimestre',
            },
        ),
        migrations.CreateModel(
            name='TerceiroBimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terceira_nota_Português', models.FloatField(verbose_name='Nota de Língua Portuguesa')),
                ('terceira_nota_Matemática', models.FloatField(verbose_name='Nota de Matemática')),
                ('terceira_nota_História', models.FloatField(verbose_name='Nota de História')),
                ('terceira_nota_Geografia', models.FloatField(verbose_name='Nota de Geografia')),
                ('terceira_nota_Ciências', models.FloatField(verbose_name='Nota de Ciências')),
                ('terceiro_bimestre_faltas', models.IntegerField(verbose_name='Faltas no Bimestre')),
            ],
            options={
                'verbose_name': 'Terceiro Bimestre',
                'verbose_name_plural': 'Terceiro Bimestre',
            },
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='notas.aluno')),
                ('primeiro_bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_bimestre', to='notas.primeirobimestre')),
                ('quarto_bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarto_bimestre', to='notas.quartobimestre')),
                ('segundo_bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_bimestre', to='notas.segundobimestre')),
                ('terceiro_bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_bimestre', to='notas.terceirobimestre')),
            ],
            options={
                'verbose_name': 'Adicionar notas ao aluno',
                'verbose_name_plural': 'Adicionar notas ao aluno',
            },
        ),
    ]
