# Generated by Django 3.2.6 on 2021-08-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeiroBimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeira_nota_Português', models.IntegerField()),
                ('primeira_nota_Matemática', models.IntegerField()),
                ('primeira_nota_História', models.IntegerField()),
                ('primeira_nota_Geografia', models.IntegerField()),
                ('primeira_nota_Ciências', models.IntegerField()),
                ('primeiro_bimestre_faltas_Português', models.IntegerField()),
                ('primeiro_bimestre_faltas_Matemática', models.IntegerField()),
                ('primeiro_bimestre_faltas_História', models.IntegerField()),
                ('primeiro_bimestre_faltas_Geografia', models.IntegerField()),
                ('primeiro_bimestre_faltas_Ciências', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuartoBimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarta_nota_Português', models.IntegerField()),
                ('quarta_nota_Matemática', models.IntegerField()),
                ('quarta_nota_História', models.IntegerField()),
                ('quarta_nota_Geografia', models.IntegerField()),
                ('quarta_nota_Ciências', models.IntegerField()),
                ('quarto_bimestre_faltas_Português', models.IntegerField()),
                ('quarto_bimestre_faltas_Matemática', models.IntegerField()),
                ('quarto_bimestre_faltas_História', models.IntegerField()),
                ('quarto_bimestre_faltas_Geografia', models.IntegerField()),
                ('quarto_bimestre_faltas_Ciências', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SegundoBimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda_nota_Português', models.IntegerField()),
                ('segunda_nota_Matemática', models.IntegerField()),
                ('segunda_nota_História', models.IntegerField()),
                ('segunda_nota_Ciências', models.IntegerField()),
                ('segundo_bimestre_faltas_Português', models.IntegerField()),
                ('segundo_bimestre_faltas_Matemática', models.IntegerField()),
                ('segundo_bimestre_faltas_História', models.IntegerField()),
                ('segundo_bimestre_faltas_Geografia', models.IntegerField()),
                ('segundo_bimestre_faltas_Ciências', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TerceiroBimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terceira_nota_Português', models.IntegerField()),
                ('terceira_nota_Matemática', models.IntegerField()),
                ('terceira_nota_História', models.IntegerField()),
                ('terceira_nota_Geografia', models.IntegerField()),
                ('terceira_nota_Ciências', models.IntegerField()),
                ('terceiro_bimestre_faltas_Português', models.IntegerField()),
                ('terceiro_bimestre_faltas_Matemática', models.IntegerField()),
                ('terceiro_bimestre_faltas_História', models.IntegerField()),
                ('terceiro_bimestre_faltas_Geografia', models.IntegerField()),
                ('terceiro_bimestre_faltas_Ciências', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='notas.aluno')),
                ('primeiro_bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_bimestre', to='notas.primeirobimestre')),
                ('quarto_bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarto_bimestre', to='notas.quartobimestre')),
                ('segundo_bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_bimestre', to='notas.segundobimestre')),
                ('terceiro_bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_bimestre', to='notas.terceirobimestre')),
            ],
        ),
    ]
