# Generated by Django 3.2.6 on 2021-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_auto_20210813_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='final',
            options={'verbose_name': 'Adicionar notas ao aluno', 'verbose_name_plural': 'Adicionar notas ao aluno'},
        ),
        migrations.AlterModelOptions(
            name='primeirobimestre',
            options={'verbose_name': 'Primeiro Bimestre', 'verbose_name_plural': 'Primeiro Bimestre'},
        ),
        migrations.AlterModelOptions(
            name='quartobimestre',
            options={'verbose_name': 'Quarto Bimestre', 'verbose_name_plural': 'Quarto Bimestre'},
        ),
        migrations.AlterModelOptions(
            name='segundobimestre',
            options={'verbose_name': 'Segundo Bimestre', 'verbose_name_plural': 'Segundo Bimestre'},
        ),
        migrations.AlterModelOptions(
            name='terceirobimestre',
            options={'verbose_name': 'Terceiro Bimestre', 'verbose_name_plural': 'Terceiro Bimestre'},
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeira_nota_Ciências',
            field=models.FloatField(verbose_name='Nota de Ciências'),
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeira_nota_Geografia',
            field=models.FloatField(verbose_name='Nota de Geografia'),
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeira_nota_História',
            field=models.FloatField(verbose_name='Nota de História'),
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeira_nota_Matemática',
            field=models.FloatField(verbose_name='Nota de Matemática'),
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeira_nota_Português',
            field=models.FloatField(verbose_name='Nota de Língua Portuguesa'),
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeiro_bimestre_faltas_Ciências',
            field=models.IntegerField(verbose_name='Faltas na aula de Ciências'),
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeiro_bimestre_faltas_Geografia',
            field=models.IntegerField(verbose_name='Faltas na aula de Geografia'),
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeiro_bimestre_faltas_História',
            field=models.IntegerField(verbose_name='Faltas na aula de História'),
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeiro_bimestre_faltas_Matemática',
            field=models.IntegerField(verbose_name='Faltas na aula de Matemática'),
        ),
        migrations.AlterField(
            model_name='primeirobimestre',
            name='primeiro_bimestre_faltas_Português',
            field=models.IntegerField(verbose_name='Faltas na aula de Língua Portuguesa'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarta_nota_Ciências',
            field=models.FloatField(verbose_name='Nota de Ciências'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarta_nota_Geografia',
            field=models.FloatField(verbose_name='Nota de Geografia'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarta_nota_História',
            field=models.FloatField(verbose_name='Nota de História'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarta_nota_Matemática',
            field=models.FloatField(verbose_name='Nota de Matemática'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarta_nota_Português',
            field=models.FloatField(verbose_name='Nota de Língua Portuguesa'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarto_bimestre_faltas_Ciências',
            field=models.IntegerField(verbose_name='Faltas na aula de Ciências'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarto_bimestre_faltas_Geografia',
            field=models.IntegerField(verbose_name='Faltas na aula de Geografia'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarto_bimestre_faltas_História',
            field=models.IntegerField(verbose_name='Faltas na aula de História'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarto_bimestre_faltas_Matemática',
            field=models.IntegerField(verbose_name='Faltas na aula de Matemática'),
        ),
        migrations.AlterField(
            model_name='quartobimestre',
            name='quarto_bimestre_faltas_Português',
            field=models.IntegerField(verbose_name='Faltas na aula de Língua Portuguesa'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segunda_nota_Ciências',
            field=models.FloatField(verbose_name='Nota de Ciências'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segunda_nota_Geografia',
            field=models.FloatField(verbose_name='Nota de Geografia'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segunda_nota_História',
            field=models.FloatField(verbose_name='Nota de História'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segunda_nota_Matemática',
            field=models.FloatField(verbose_name='Nota de Matemática'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segunda_nota_Português',
            field=models.FloatField(verbose_name='Nota de Língua Portuguesa'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segundo_bimestre_faltas_Ciências',
            field=models.IntegerField(verbose_name='Faltas na aula de Ciências'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segundo_bimestre_faltas_Geografia',
            field=models.IntegerField(verbose_name='Faltas na aula de Geografia'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segundo_bimestre_faltas_História',
            field=models.IntegerField(verbose_name='Faltas na aula de História'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segundo_bimestre_faltas_Matemática',
            field=models.IntegerField(verbose_name='Faltas na aula de Matemática'),
        ),
        migrations.AlterField(
            model_name='segundobimestre',
            name='segundo_bimestre_faltas_Português',
            field=models.IntegerField(verbose_name='Faltas na aula de Língua Portuguesa'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceira_nota_Ciências',
            field=models.FloatField(verbose_name='Nota de Ciências'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceira_nota_Geografia',
            field=models.FloatField(verbose_name='Nota de Geografia'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceira_nota_História',
            field=models.FloatField(verbose_name='Nota de História'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceira_nota_Matemática',
            field=models.FloatField(verbose_name='Nota de Matemática'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceira_nota_Português',
            field=models.FloatField(verbose_name='Nota de Língua Portuguesa'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceiro_bimestre_faltas_Ciências',
            field=models.IntegerField(verbose_name='Faltas na aula de Ciências'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceiro_bimestre_faltas_Geografia',
            field=models.IntegerField(verbose_name='Faltas na aula de Geografia'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceiro_bimestre_faltas_História',
            field=models.IntegerField(verbose_name='Faltas na aula de História'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceiro_bimestre_faltas_Matemática',
            field=models.IntegerField(verbose_name='Faltas na aula de Matemática'),
        ),
        migrations.AlterField(
            model_name='terceirobimestre',
            name='terceiro_bimestre_faltas_Português',
            field=models.IntegerField(verbose_name='Faltas na aula de Língua Portuguesa'),
        ),
    ]
